Adicionando componentes do SideBar
pab-h/LogicLab pull request #9
Opened 2024-06-18 18:58 UTC by Miguel-Edson

Fazendo o pull request pufavo de certo

2024-06-18 21:40 UTC, pab-h requested changes
O código está ótimo. Notei só alguns detalhes <3 <3

Também achei um bug:

https://github.com/pab-h/LogicLab/assets/74771892/cfb785fc-5607-49cc-89ac-245e7dbc2be0

2024-06-18 21:40 UTC, pab-h commented on logiclab-app/src/ui/sideBar.js
Lembre-se de remover os `console.log`. No caso: `console.log('Tabela clicked, state is now:', !tabela);`. Não podem passar para a produção

2024-06-18 21:40 UTC, pab-h commented on logiclab-app/src/ui/sideBar.js
Para manter o padrão, verifique sempre os ; já que você está usando. Há algumas linhas que não tem. Por exemplo: 19, 25, 32 e 39

2024-06-19 17:16 UTC, Miguel-Edson commented on logiclab-app/src/ui/sideBar.js
Resolvido S2

2024-06-19 17:16 UTC, Miguel-Edson commented on logiclab-app/src/ui/sideBar.js
Resolvido S2

2024-06-22 00:57 UTC, pab-h reviewed
asmei

2024-06-22 00:57 UTC, pab-h reviewed
Amei 2

2024-06-22 12:20 UTC, merged